name: Railway Preview Deployment

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  deploy_preview:
    runs-on: ubuntu-latest
    if: ${{ github.event.action != 'closed' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Railway (Preview Environment)
        uses: ayungavis/railway-preview-deploy@v1.0.2
        with:
          railway_api_token: ${{ secrets.RAILWAY_TOKEN }}
          project_id: ${{ secrets.RAILWAY_PROJECT_ID }}
          environment_name: 'staging'
          preview_environment_name: 'pr-${{ github.event.pull_request.number }}'
          branch_name: ${{ github.head_ref }}

  cleanup_preview:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true || github.event.action == 'closed' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cleanup Railway Environment
        uses: ayungavis/railway-preview-deploy@v1.0.2
        with:
          railway_api_token: ${{ secrets.RAILWAY_TOKEN }}
          project_id: ${{ secrets.RAILWAY_PROJECT_ID }}
          environment_name: 'staging'  # Specify the environment to target for cleanup
          preview_environment_name: 'pr-${{ github.event.pull_request.number }}'
          branch_name: ${{ github.head_ref }}
          cleanup: 'true'

  deploy_staging:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Railway (Staging)
        uses: ayungavis/railway-preview-deploy@v1.0.2
        with:
          railway_api_token: ${{ secrets.RAILWAY_TOKEN }}
          project_id: ${{ secrets.RAILWAY_PROJECT_ID }}
          environment_name: 'staging'
          branch_name: ${{ github.head_ref }}  # Use the PR branch name or default branch name if needed
          preview_environment_name: 'staging'  # You can use 'staging' or another descriptive name here

  deploy_production:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true }}
    needs: deploy_staging
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Railway (Production)
        uses: ayungavis/railway-preview-deploy@v1.0.2
        with:
          railway_api_token: ${{ secrets.RAILWAY_TOKEN }}
          project_id: ${{ secrets.RAILWAY_PROJECT_ID }}
          environment_name: 'production'
          branch_name: 'main'  # Use the main branch or another branch used for production
          preview_environment_name: 'production'  # Use a meaningful, descriptive name
